baseURL = 'https://spectacular-entremet-d9ca9d.netlify.app/'
languageCode = 'sv-se'
title = 'My New Hugo Site'
theme = 'ananke'

SectionPagesMenu = "main"

[params]
    background_color_class = "bg-blue"